name: "Changed Files Exporter"
github-token:
  action-input: 
    token: repo-token
    is-default: true
  permissions:
    contents: write
    contents-reason: to write 
    pull-requests: read
    pull-requests-reason: to get list of files

#Reference -https://github.com/umani/changed-files/blob/96d5fd702a6479d573287ef07381ad59acc390ed/src/main.ts#L95
