name: 'Deployment Action'
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    contents: write
    contents-reason: to create deployment action

#Reference - https://github.com/chrnorm/deployment-action/blob/3afecce166a0a2f92d3a9e7351a9908a72121c24/lib/main.js
