name: 'Action Check Typescript errors'
github-token:
  action-input:
    input: repo-token
    is-default: false
  permissions:
    pull-requests: write
    pull-requests-reason: to create review
    issues: write
    issues-reason: to create comments

#reference-https://github.com/Arhia/action-check-typescript/blob/d1a7bbe877766c64f1703a48cd707b13488fdae3/src/main.ts#L46
