name: "sarif-to-issue-action"
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: true
  permissions:
    issues: write
    issues-reason: to run the scan that generates a SARIF file


#https://github.com/sett-and-hive/sarif-to-issue-action/blob/32fe9c4d9595403bb4a559727e7ee7e9c49e4538/README.md#branch
