name: Gitleaks
github-token:
  environment-variable-name: GITHUB_TOKEN
    is-default: false
  permissions:
    pull-requests: write
    pull-requests-reason: to scan pull requests
    contents: read
    contents-reason: to read comments

#Reference: https://github.com/gitleaks/gitleaks-action/blob/d858f0e53c0be207bc6f2c5d5218913c1862b881/src/gitleaks.js#L154


