name: "Handling CLAs and DCOs via GitHub Action"
github-token:
  environment-variable-name: GITHUB_TOKEN
  permissions:
    contents: write
    contents-reason: to sign CLAs from within a pull request
    pull-requests: write 
    pull-requests-reason: to get specific PR
    actions: write 
    actions-reason: to make the API calls for interacting with GitHub
    issues: write 
    issues-reason: to create issue comment

#Reference: https://github.com/contributor-assistant/github-action/blob/b3bbab0a75fa27270069933cec6f369c0b373b4e/src/octokit.ts#L3
