name: 'Deployment Status'
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    contents: write
    contents: to create deployment status

#Reference - https://github.com/chrnorm/deployment-status/blob/07b3930847f65e71c9c6802ff5a402f6dfb46b86/lib/main.js
