name: Changed Files
github-token:
  action-input:
    input: PAT_TOKEN
    is-default: true
  permsissions:
    pull-requests: read
    pull-request-reason: to Get the last successful commit

#Checkout: https://github.com/tj-actions/changed-files/blob/086ffa020e34021d007625f8e08a82488e51852d/README.md
#1098