name: Code Coverage Report
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: true
  permissions:
    contents: read
    contents-reason: to post the comment

#Reference - https://github.com/eberlitz/lcov-reporter-action
