name: Close issues after no reply
github-token:
  action-input: 
    input: repo-token
    is-default: true
  permissions:
    issues: read
    issues-reason: to read and list all issues

#checkout: https://github.com/imhoffd/needs-reply/blob/71e8d5144caa0d4a1e292348bfafa3866d08c855/src/index.ts#L19

