name: Test Reporter
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    checks: write
    checks-reason: to create and update response
    actions: read
    actions-reason: to share data between jobs and store data once a workflow is complete
    contents: read
    contents-reason: to read contents

#Reference - https://github.com/dorny/test-reporter/blob/0d9714ddc7ff86918ec725a527a3a069419d301a/src/main.ts#L50
